"""add_prompt_to_playlists

Revision ID: 43f21411eb2e
Revises: 28ee643b3551
Create Date: 2026-03-13 17:15:05.322185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f21411eb2e'
down_revision: Union[str, Sequence[str], None] = '28ee643b3551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('prompt', sa.String(length=500), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'prompt')
    # ### end Alembic commands ###
